use_frameworks!

platform :ios, '10.0'

target 'ZLTabBarExtension_Example' do
  pod 'ZLTabBarExtension', :path => '../'

  target 'ZLTabBarExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
